#!/bin/bash
export CONFIG_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"
#left
#lua
source "$ITEM_DIR/weather.sh"
#center
source "$ITEM_DIR/calendar.sh"

#right
#source "$ITEM_DIR/cron.sh"
source "$ITEM_DIR/reminders.sh"
source "$ITEM_DIR/input_source.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
#source "$ITEM_DIR/caffeinate.sh"
source "$ITEM_DIR/network_rates.sh"
source "$ITEM_DIR/now_playing.sh"
sketchybar --update

make -s -C "$CONFIG_DIR/helpers/input_source" bin/input_source
"$CONFIG_DIR/helpers/input_source/bin/input_source" "$(command -v sketchybar)" &
[ -x "$CONFIG_DIR/helpers/menus/bin/menus" ] || make -C "$CONFIG_DIR/helpers/menus" bin/menus
exec lua "$CONFIG_DIR/lua/init.lua"
